[package]
name = "hassle-rs"
version = "0.1.0"
authors = ["Jasper-Bekkers <bekkers@gmail.com>"]
edition = "2018"
description = "This crate provides an FFI layer and idiomatic rust wrappers for the new DXC hlsl compiler."
license = "mit"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/Jasper-Bekkers/hassle-rs"
repository = "https://github.com/Jasper-Bekkers/hassle-rs"
keywords = ["rendering", "shader", "pipeline", "hlsl", "dxc"]
categories = ["rendering", "rendering::graphics-api"]
include = [
    "src/*.rs",
    "Cargo.toml",
]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
libloading = "0.5.0"
com-rs = "0.2.0"
winapi = "0.3.6"